-- Datos de partida para DE/FR/IT/PT/UK.
-- source = 'manual_seed' -> NO verificado contra la fuente oficial del pais.
-- Sustituir por integracion real cuando investiguemos cada agencia nacional.
-- La columna form es la forma prevista del producto de ejemplo, para que se
-- compare con productos de España de la misma forma (nomenclatura de CIMA).
-- Los ejemplos de clorhexidina son enjuagues bucales (parafarmacia): CIMA no
-- tiene ninguno sin receta (solo antisépticos cutáneos), así que llevan form
-- vacío para no emparejarlos con un producto de otra forma.

INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'DE', 'Otowaxol Ohrentropfen', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'docusato sódico';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'FR', 'Cerulyse', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'docusato sódico';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'IT', 'Cerumex Gocce', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'docusato sódico';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'PT', 'Otex Gotas', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'docusato sódico';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'UK', 'Earex Plus', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'docusato sódico';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'DE', 'Vomex A', 0, 'manual_seed', date('now'), 'COMPRIMIDO' FROM active_ingredients WHERE inn_name = 'dimenhidrinato';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'FR', 'Nautamine', 0, 'manual_seed', date('now'), 'COMPRIMIDO' FROM active_ingredients WHERE inn_name = 'dimenhidrinato';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'IT', 'Xamamina', 0, 'manual_seed', date('now'), 'COMPRIMIDO' FROM active_ingredients WHERE inn_name = 'dimenhidrinato';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'PT', 'Enjomin', 0, 'manual_seed', date('now'), 'COMPRIMIDO' FROM active_ingredients WHERE inn_name = 'dimenhidrinato';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'UK', 'Dramamine (import)', 0, 'manual_seed', date('now'), 'COMPRIMIDO' FROM active_ingredients WHERE inn_name = 'dimenhidrinato';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'DE', 'Voltaren Schmerzgel Forte', 1, 'manual_seed', date('now'), 'GEL' FROM active_ingredients WHERE inn_name = 'diclofenaco';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'FR', 'Voltarène Emulgel', 0, 'manual_seed', date('now'), 'GEL' FROM active_ingredients WHERE inn_name = 'diclofenaco';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'IT', 'Dolorfast Gel', 0, 'manual_seed', date('now'), 'GEL' FROM active_ingredients WHERE inn_name = 'diclofenaco';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'PT', 'Voltaren Emulgel', 0, 'manual_seed', date('now'), 'GEL' FROM active_ingredients WHERE inn_name = 'diclofenaco';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'UK', 'Voltarol 12 Hour', 0, 'manual_seed', date('now'), 'GEL' FROM active_ingredients WHERE inn_name = 'diclofenaco';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'DE', 'Hansaplast Wundheilung', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (cicatrizante)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'FR', 'Urgo Cicatrisant', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (cicatrizante)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'IT', 'Hansaplast Cicatrizzante', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (cicatrizante)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'PT', 'Cicaplast Penso', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (cicatrizante)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'UK', 'Hansaplast Wound Healing', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (cicatrizante)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'DE', 'Compeed Blasenpflaster', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (ampollas)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'FR', 'Compeed Ampoules', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (ampollas)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'IT', 'Compeed Vesciche', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (ampollas)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'PT', 'Compeed Bolhas', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (ampollas)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'UK', 'Compeed Blister Plasters', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'apósito hidrocoloide (ampollas)';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'DE', 'Chlorhexamed Fluid', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'clorhexidina';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'FR', 'Eludril', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'clorhexidina';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'IT', 'Curasept', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'clorhexidina';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'PT', 'Eludril Bucal', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'clorhexidina';
INSERT OR IGNORE INTO products (active_ingredient_id, country_code, brand_name, requires_prescription, source, verified_at, form) SELECT id, 'UK', 'Corsodyl Mouthwash', 0, 'manual_seed', date('now'), NULL FROM active_ingredients WHERE inn_name = 'clorhexidina';
